### ISSUE TITLE
 Clarification on UBEC Assembly in Body Module

### ISSUE THREAD

**Issue by lixinyao11** [apirrone/Open_Duck_Mini#1]
Hi there,

Thank you for sharing this fantastic project! I’ve been working on building a robot following your design on Onshape. However, I noticed that the UBEC part is not included in the body module, even though it is listed in the BOM and Parts tab. Additionally, based on your wiring diagram, the UBEC seems to be a necessary component for the body assembly.

Could you kindly advise on how to assemble the UBEC in the body module? Alternatively, if possible, could the Onshape page be updated to include this information?

Thank you for your time and assistance! I really appreciate your efforts in making this project accessible.

**Comment by apirrone** [comment]
Hi! 

Yeah, the UBEC module is just stuffed in the back of the robot, there is space in the cavity below the u2d2 power board. It's not great design 😅

I should add this in the readme, but I would advise waiting (a few months probably) for the v2 version instead of building the current version. We'll start the design soon, it should be cheaper, better designed and easier to build (with better docs too). If you already started building the current version, I'll help you make things work of course !

Thanks !

**Comment by lixinyao11** [comment]
Hi!

Thank you for your help! I have already started building the current version and I will try to make things work! Also looking forward to your v2 version! : )
